//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_PlasmaVR : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Vector2 PointerDistance
        {
            get
            {
                return SteamVR_Actions.plasmaVR_PointerDistance;
            }
        }
        
        public virtual SteamVR_Action_Boolean Select
        {
            get
            {
                return SteamVR_Actions.plasmaVR_Select;
            }
        }
        
        public virtual SteamVR_Action_Boolean Rotate
        {
            get
            {
                return SteamVR_Actions.plasmaVR_Rotate;
            }
        }
        
        public virtual SteamVR_Action_Boolean Draw
        {
            get
            {
                return SteamVR_Actions.plasmaVR_Draw;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.plasmaVR_Menu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Move
        {
            get
            {
                return SteamVR_Actions.plasmaVR_Move;
            }
        }
        
        public virtual SteamVR_Action_Boolean Sprint
        {
            get
            {
                return SteamVR_Actions.plasmaVR_Sprint;
            }
        }
        
        public virtual SteamVR_Action_Boolean VerticalMoveToggle
        {
            get
            {
                return SteamVR_Actions.plasmaVR_VerticalMoveToggle;
            }
        }
    }
}
